[package]
name = "crud-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
crud = { path = "../crud" }

cruet = "0.13.3"
quote = "1.0.26"
syn = "2.0.15"
